# Generated by Django 4.1.7 on 2023-07-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_employee', '0004_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
