# Generated by Django 4.1.7 on 2023-08-01 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp_employee', '0009_timesheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='employee',
            new_name='emp_data',
        ),
    ]
