# Generated by Django 4.1.7 on 2023-08-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp_employee', '0010_rename_employee_timesheet_emp_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='emp_data',
        ),
    ]
